const TASKS_TEMPLATE = [
  /* ── MISSIONS ─────────────────────────────────── */
  {
    id:          'first_blood',
    category:    'mission',
    icon:        '⚔️',
    title:       'First Blood',
    desc:        'Kill your first enemy.',
    goal:        1,
    rewardType:  'shards',
    rewardValue: 50,
    trackEvent:  'ENEMY_KILLED',
    increment:   () => 1,
  },
  {
    id:          'soul_harvester',
    category:    'mission',
    icon:        '💀',
    title:       'Soul Harvester',
    desc:        'Kill 100 enemies across all runs.',
    goal:        100,
    rewardType:  'shards',
    rewardValue: 300,
    trackEvent:  'ENEMY_KILLED',
    increment:   () => 1,
  },
  {
    id:          'tier3_slayer',
    category:    'mission',
    icon:        '🔴',
    title:       'Apex Predator',
    desc:        'Kill 25 Tier-3 elite enemies.',
    goal:        25,
    rewardType:  'shards',
    rewardValue: 250,
    trackEvent:  'ELITE_KILLED',
    increment:   () => 1,
  },
  /* ── ACHIEVEMENTS ──────────────────────────────── */
  {
    id:          'untouchable',
    category:    'achievement',
    icon:        '🛡️',
    title:       'Untouchable',
    desc:        'Survive 2 minutes in a single run without taking damage.',
    goal:        120,           // seconds
    rewardType:  'shards',
    rewardValue: 500,
    trackEvent:  'TIME_SURVIVED_NODMG',
    increment:   (payload) => payload.dt,   // accumulates delta-seconds
  },
  {
    id:          'rich_reaper',
    category:    'achievement',
    icon:        '💰',
    title:       'Rich Reaper',
    desc:        'Hold 5,000 Soul Shards at once.',
    goal:        1,             // binary: completed once threshold crossed
    rewardType:  'skin',
    rewardValue: 'golden_tail', // skin id – added to SKIN_CATALOGUE below
    trackEvent:  'SHARD_BALANCE_UPDATED',
    increment:   (payload) => (payload.balance >= 5000 ? 1 : 0),
  },
  {
    id:          'level_10',
    category:    'achievement',
    icon:        '🌀',
    title:       'Ascendant',
    desc:        'Reach Level 10 in a single run.',
    goal:        1,
    rewardType:  'shards',
    rewardValue: 350,
    trackEvent:  'LEVEL_REACHED',
    increment:   (payload) => (payload.level >= 10 ? 1 : 0),
  },
  {
    id:          'upgrade_5',
    category:    'achievement',
    icon:        '⬆️',
    title:       'Soul Architect',
    desc:        'Collect 5 upgrades in a single run.',
    goal:        1,
    rewardType:  'shards',
    rewardValue: 200,
    trackEvent:  'UPGRADES_COLLECTED',
    increment:   (payload) => (payload.count >= 5 ? 1 : 0),
  },
  /* ── DAILY ─────────────────────────────────────── */
  {
    id:          'daily_bounty',
    category:    'daily',
    icon:        '📅',
    title:       'Daily Bounty',
    desc:        'Complete 3 runs today. Resets at midnight.',
    goal:        3,
    rewardType:  'shards',
    rewardValue: 150,
    trackEvent:  'RUN_COMPLETED',
    increment:   () => 1,
    isDaily:     true,
    adDoubleReward: false,
  },
  {
    id:          'daily_killer',
    category:    'daily',
    icon:        '🗡️',
    title:       "Reaper's Quota",
    desc:        'Kill 50 enemies today.',
    goal:        50,
    rewardType:  'shards',
    rewardValue: 120,
    trackEvent:  'ENEMY_KILLED',
    increment:   () => 1,
    isDaily:     true,
  },
];

/* ═══════════════════════════════════════════════════════
   TASK MANAGER
═══════════════════════════════════════════════════════ */
